/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.ListaSimpleNormalCalificacion;
import Clases.ListaSimpleNormalEstudiante;
import Clases.ListaSimpleNormalMateria;

/**
 *
 * @author print
 */
public class Ventana extends javax.swing.JFrame {

    private ListaSimpleNormalMateria A=new ListaSimpleNormalMateria();
    private ListaSimpleNormalEstudiante B=new ListaSimpleNormalEstudiante();

   

    public ListaSimpleNormalEstudiante getB() {
        return B;
    }

    public ListaSimpleNormalMateria getA() {
        return A;
    }

    public void setA(ListaSimpleNormalMateria A) {
        this.A = A;
    }

   

    public void setB(ListaSimpleNormalEstudiante B) {
        this.B = B;
    }
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrar = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        mostrarMat = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adiMat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrar.setText("Mostrar Estudiantes");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        adicionar.setText("Adicionar Estudiantes");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });
        getContentPane().add(adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        mostrarMat.setText("Mostrar Materias");
        mostrarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMatActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel1.setText("Registro de datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        adiMat.setText("Adicionar Materia");
        adiMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiMatActionPerformed(evt);
            }
        });
        getContentPane().add(adiMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        MostrarEstudiante v2=new MostrarEstudiante(this);
        v2.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_mostrarActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        // TODO add your handling code here:
        AdiEstudiantes v2=new AdiEstudiantes(this);
        v2.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_adicionarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void adiMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiMatActionPerformed
        // TODO add your handling code here:
        
        adiMateria v2=new adiMateria(this);
        v2.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_adiMatActionPerformed

    private void mostrarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMatActionPerformed
        // TODO add your handling code here:
        MostrarMateria v2=new MostrarMateria(this);
        v2.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_mostrarMatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adiMat;
    private javax.swing.JButton adicionar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostrar;
    private javax.swing.JButton mostrarMat;
    // End of variables declaration//GEN-END:variables
}
